dataSource:
  driverClassName: com.mysql.jdbc.Driver
  dbCreate: update
  username: root
  password: password
environments:
  development:
    dataSource:
      dbCreate: update
      url: "jdbc:mysql://localhost/abc?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"